d

diff --git a/.github/workflows/StartMeManually.yml b/.github/workflows/StartMeManually.yml
--- a/.github/workflows/StartMeManually.yml
+++ b/.github/workflows/StartMeManually.yml
@@ -28,7 +28,7 @@ jobs:
           $moduleName=Get-ChildItem -Directory |Where-Object {Test-Path (Join-Path $_ "$($_.name).psd1")}|Select-Object -ExpandProperty Name
           echo "MODULENAME=$moduleName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
           $psdModuleVersion=Import-PowerShellDataFile (Join-Path $moduleName "$moduleName.psd1")|Select-Object -ExpandProperty ModuleVersion
-          echo "PSD_MODULEVERSION=$psdModuleVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append      shell: pwsh
+          echo "PSD_MODULEVERSION=$psdModuleVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
       - name: Install GitVersion
         uses: gittools/actions/gitversion/setup@v0.9.15
         with:
@@ -38,3 +38,6 @@ jobs:
         uses: gittools/actions/gitversion/execute@v0.9.15
         with:
           next_version: 2.0.0
+      # - name: Setup tmate session
+      #   if: ${{ failure() || (github.event_name == 'workflow_dispatch' && inputs.debug_enabled ) }}
+      #   uses: mxschmitt/action-tmate@v3
