Print Context added

diff --git a/.github/workflows/StartMeManually.yml b/.github/workflows/StartMeManually.yml
--- a/.github/workflows/StartMeManually.yml
+++ b/.github/workflows/StartMeManually.yml
@@ -18,26 +18,28 @@ jobs:
         shell: pwsh
     steps:
       - name: Print Environment
-        uses: managedkaos/print-env@master
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Get ModuleName
-        run: |
-          $moduleName=Get-ChildItem -Directory |Where-Object {Test-Path (Join-Path $_ "$($_.name).psd1")}|Select-Object -ExpandProperty Name
-          echo "MODULENAME=$moduleName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
-          $psdModuleVersion=Import-PowerShellDataFile (Join-Path $moduleName "$moduleName.psd1")|Select-Object -ExpandProperty ModuleVersion
-          echo "PSD_MODULEVERSION=$psdModuleVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
-      - name: Install GitVersion
-        uses: gittools/actions/gitversion/setup@v0.9.15
-        with:
-          versionSpec: '5.x'
-      - name: Determine Version
-        id: gitversion
-        uses: gittools/actions/gitversion/execute@v0.9.15
-        with:
-          additionalArguments: /overrideconfig next-version=${{env.PSD_MODULEVERSION}}
-      # - name: Setup tmate session
-      #   if: ${{ failure() || (github.event_name == 'workflow_dispatch' && inputs.debug_enabled ) }}
-      #   uses: mxschmitt/action-tmate@v3
+        uses: ./.github/workflows/PrintContext.yml@development
+      # - name: Print Environment
+      #   uses: managedkaos/print-env@master
+      # - name: Checkout
+      #   uses: actions/checkout@v3
+      #   with:
+      #     fetch-depth: 0
+      # - name: Get ModuleName
+      #   run: |
+      #     $moduleName=Get-ChildItem -Directory |Where-Object {Test-Path (Join-Path $_ "$($_.name).psd1")}|Select-Object -ExpandProperty Name
+      #     echo "MODULENAME=$moduleName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+      #     $psdModuleVersion=Import-PowerShellDataFile (Join-Path $moduleName "$moduleName.psd1")|Select-Object -ExpandProperty ModuleVersion
+      #     echo "PSD_MODULEVERSION=$psdModuleVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+      # - name: Install GitVersion
+      #   uses: gittools/actions/gitversion/setup@v0.9.15
+      #   with:
+      #     versionSpec: '5.x'
+      # - name: Determine Version
+      #   id: gitversion
+      #   uses: gittools/actions/gitversion/execute@v0.9.15
+      #   with:
+      #     additionalArguments: /overrideconfig next-version=${{env.PSD_MODULEVERSION}}
+      # # - name: Setup tmate session
+      # #   if: ${{ failure() || (github.event_name == 'workflow_dispatch' && inputs.debug_enabled ) }}
+      # #   uses: mxschmitt/action-tmate@v3
